<a href="https://colab.research.google.com/github/ankitrijal2054/CPSMA-441301/blob/main/Gauss_Jordan_Elimination.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Project 4: Gauss-Jordan Elimination

$Ankit Rijal$

$Min Sun Kim$

$Tylar Gifford$

$CPSMA - 441301$

$Dr. Nicolas Jacob$

##Gauss-Jordan Algorithm

Gauss-Jordan algorithm is used to solve equations similar to this form,



$$
\left\{
\begin{align}
a_{1,1} x_1 +&\dots a_{1,n} x_n = y_1\\
&\vdots\\
a_{n,1}x_1+&\dots a_{n,n} x_n = y_n
\end{align}
\right.
$$



Let's use Gauss-Jordan algorithm to solve the following algorithm

$$
x+3y+z = 10\\
x-2y-z = -6\\
2x+y+2z = 10
$$

First we need to break it down to an augmented matrix

$$
\left[
\begin{array}{ccc|c}
1 & 3 & 1 & 10\\
1 & -2 & -1 & -6\\
2 & 1 & 2 & 10
\end{array}
\right]
$$


First I'm going to import necessary module for this project.

In [ ]:
#importing necessary modules
import math
import numpy as np

Then, I'm going to create a matrix mat with above values.

In [ ]:
mat = np.array([[1,3,1,10],[1,-2,-1,-6],[2,1,2,10]]) 

print(mat)

[[ 1  3  1 10]
 [ 1 -2 -1 -6]
 [ 2  1  2 10]]


Now, I am going to write the function for swapping rows.

In [ ]:
def swap(matrix, row1, row2):
  swapped_matrix = []
  size = len(matrix)      #to find the size of a matrix
  for i in range(size):   #using loop to go through each row
    if i == row1:
      swapped_matrix.append(matrix[row2,:])   
    elif i == row2:
      swapped_matrix.append(matrix[row1,:])
    else:
      swapped_matrix.append(matrix[i,:])
  return np.array(swapped_matrix)


Let's try if our function works or not.

In [ ]:
swap(mat, 0, 2)

array([[ 2,  1,  2, 10],
       [ 1, -2, -1, -6],
       [ 1,  3,  1, 10]])

Secondly, I am going to define the function for adding two rows of a matrix.

---



In [ ]:
def add_rows(matrix, target_row, adding_row, multiplier):
  added_matrix = []
  size = len(matrix)
  for i in range(size):   #using loop to go through each row
    if i == target_row:
      old_row = matrix[target_row,:]
      adding_values = multiplier * matrix[adding_row,:]
      new_row = old_row + adding_values
      added_matrix.append(new_row)
    else:
      added_matrix.append(matrix[i,:])
  return np.array(added_matrix)

Let's check this function by multiplying row 3 of mat and adding it to row 1.

In [ ]:
add_rows(mat, 0, 2, 2)

array([[ 5,  5,  5, 30],
       [ 1, -2, -1, -6],
       [ 2,  1,  2, 10]])

And now, I am going to write the function for multiplying user defined row by a user defined constant.

In [ ]:
def multiply(matrix, target_row, constant):
  new_matrix = []
  size = len(matrix)
  for i in range(size):   #using loop to go through each row
    if i == target_row:
      new_matrix.append(constant * matrix[target_row,:])
    else:
      new_matrix.append(matrix[i,:])
  return np.array(new_matrix)

Let's check this function by multiplying row 2 of mat by 3.

In [ ]:
multiply(mat, 1, 3)

array([[  1,   3,   1,  10],
       [  3,  -6,  -3, -18],
       [  2,   1,   2,  10]])

According to the Gauss-Jordan algorithm, the first step is to swap the rows so that the row with the largest, leftmost nonzero value is on top.
For that, we are going to write a function to find the row with largest leftmost value to swap it with the current row.

In [ ]:
def max_value_row(matrix, column):
  col = matrix[column:,column]
  max = 0
  for i in range(len(col)):
    if col[max] < col[i]:
      max = i
  max_row = max + column
  return max_row

Let's check the function.

In [ ]:
max_value_row(mat, 0)

2

Once we use Gauss-Jordan elimination, our matrix mat should look like below and the last column will give us the value of x, y and z.
$$
\left[
\begin{array}{cccc}
1 & 0 & 0 & 1 \\
0 & 1 & 0 & 2\\
0 & 0 & 1 & 3
\end{array}
\right]
$$

\\
$$
x=1, y=2, z=3
$$

Now, using all the above functions I'm going to write a Gauss-Jordan function to solve the linear equation.

In [ ]:
def gaussJordan(matrix):
  for i in range(len(matrix)):  #using loop to go through each row
    pos = max_value_row(matrix, i)  #using max_value_row function to find the row with largest leftmost value   
    matrix = swap(matrix, pos, i)   #swapping current row with row found on previous step   
    constant = 1/matrix[i,i]        
    matrix = multiply(matrix,i,constant)  #using multiply function to make the diagonal 1
    for column in range(0,i):             
      matrix = add_rows(matrix,column,i,-matrix[column,i])    #using add_rows function to make all values except diagonal 0
    for column in range(i+1,len(matrix)):
      matrix = add_rows(matrix,column,i,-matrix[column,i])    #using add_rows function to make all values except diagonal 0
  return np.array(matrix)

Now, let's use our Gauss-Jordan function to calculate the value of x, y and z of the function abave.

In [ ]:
gaussJordan(mat)

array([[ 1.,  0.,  0.,  1.],
       [ 0.,  1.,  0.,  2.],
       [-0., -0.,  1.,  3.]])

We have sucessfully created a Gauss-Jordan function to solve the linear equation. However, this function has its own limitation.
$$
\\
$$
Let's try to solve the following equation:
$$
x-2y = 2\\
2x-4y = 4\\
\\
$$


In [ ]:
new_mat = np.array([[1,-2,2],[2,-4,4]]) 
gaussJordan(new_mat)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  """
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in multiply
  


array([[nan, nan, nan],
       [nan, nan, nan]])

We are getting this error because on the above equation, values of x depends on values of y and vice versa. That means the above function can have infinite different solution. But our function can only solve a equation with one unique solution. So, this is the limitation of our Gauss-Jordan function.